# Generated by Django 4.1.2 on 2023-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_dat', models.DateTimeField()),
                ('end_Data', models.DateTimeField()),
                ('code_exp', models.CharField(max_length=500)),
                ('codeinput', models.CharField(max_length=200)),
                ('codeoutput', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sub_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=50)),
                ('sub_time', models.CharField(max_length=50)),
                ('codeTitel', models.CharField(max_length=250)),
                ('sub_lang', models.CharField(default='', max_length=50)),
                ('sub_data', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='userVisitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(default='', max_length=50)),
                ('codeId', models.IntegerField()),
                ('stTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='winnerSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Sub_time', models.CharField(max_length=50)),
            ],
        ),
    ]
