# Generated by Django 4.1.2 on 2023-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualLab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeId', models.IntegerField()),
                ('testInp', models.CharField(default='', max_length=50)),
                ('testOut', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
