# Generated by Django 4.1.2 on 2023-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examCell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestions',
            name='examId',
            field=models.IntegerField(),
        ),
    ]
